apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadbal
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: load-balancer
    repoURL: 'https://github.com/ArnaudPizz/ArgoCD'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated: {}
